export default function PrivacyPage() {
  return (
    <div className="legal-shell">
      <div className="legal-card">
        <h1>Privacy Policy</h1>
        <p>
          <strong>Effective Date:</strong> [Insert Date]
        </p>
        <p>
          Welcome to NEXA (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). Your
          privacy is important to us. This Privacy Policy explains how we collect,
          use, and protect your information when you use our application.
        </p>

        <h2>1. Information We Collect</h2>
        <p>We may collect the following types of information:</p>

        <h2>a. Account Information</h2>
        <ul>
          <li>Name (if provided)</li>
          <li>Email address</li>
          <li>Authentication details (via third-party providers like Supabase)</li>
        </ul>

        <h2>b. Usage Data</h2>
        <ul>
          <li>Interactions with the app (e.g., goals selected, prompts entered)</li>
          <li>Feature usage and activity logs</li>
          <li>Device/browser information (IP address, user agent)</li>
        </ul>

        <h2>c. Generated Content</h2>
        <ul>
          <li>Inputs you provide</li>
          <li>Outputs generated by the AI system</li>
        </ul>

        <h2>2. How We Use Your Information</h2>
        <p>We use your data to:</p>
        <ul>
          <li>Provide and improve the NEXA experience</li>
          <li>Generate personalized plans, actions, and outputs</li>
          <li>Monitor performance and fix issues</li>
          <li>Analyze usage trends to improve features</li>
          <li>Ensure security and prevent misuse</li>
        </ul>

        <h2>3. Data Storage and Security</h2>
        <ul>
          <li>
            Your data may be stored securely using third-party services (e.g.,
            Supabase, cloud providers)
          </li>
          <li>We implement reasonable safeguards to protect your information</li>
          <li>However, no system is 100% secure</li>
        </ul>

        <h2>4. Third-Party Services</h2>
        <p>We may use third-party services for:</p>
        <ul>
          <li>Authentication</li>
          <li>Data storage</li>
          <li>AI processing</li>
        </ul>
        <p>
          These services may process your data according to their own privacy
          policies.
        </p>

        <h2>5. Data Retention</h2>
        <p>We retain your data only as long as necessary to:</p>
        <ul>
          <li>Provide services</li>
          <li>Improve the product</li>
          <li>Comply with legal obligations</li>
        </ul>

        <h2>6. Your Rights</h2>
        <p>You may:</p>
        <ul>
          <li>Request access to your data</li>
          <li>Request deletion of your data</li>
          <li>Contact us for any privacy concerns</li>
        </ul>
        <p>Contact: [your email]</p>

        <h2>7. Children&apos;s Privacy</h2>
        <p>
          NEXA is not intended for users under 13. We do not knowingly collect
          data from children.
        </p>

        <h2>8. Changes to This Policy</h2>
        <p>
          We may update this policy. Continued use of NEXA means you accept the
          updated terms.
        </p>

        <h2>9. Contact</h2>
        <p>If you have questions:</p>
        <p>Email: [your email]</p>

        <p>By using NEXA, you agree to this Privacy Policy.</p>
      </div>
    </div>
  );
}
